apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: website
spec:
  type: NodePort
  selector:
    app: personal-website
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 80
        targetPort: 80